### PR TITLE
Change column "highlight" method to "highlight_commands" method

### LINKED ISSUE #73: Defx blinking and slowly rerendering when focused
# Problems summary
Since latest commit https://github.com/Shougo/defx.nvim/commit/ec512a6aca968427258efe75b31de734c9295179 where you added async action for opening defx, it is behaving strangely. Because of the async nature, it blinks when focused. I didn't had this issue before.

Also, note that i'm using 2 custom columns. When i remove them, it is better, but still noticable when switching focus fast.

## Expected
Expected not to blink.

## Environment Information

 * defx version(SHA1): ec512a6aca968427258efe75b31de734c9295179

 * OS: Manjaro Linux i3

 * neovim/Vim version: NVIM v0.4.0-242-ged0e96cd2

 * `:checkhealth` or `:CheckHealth` result(neovim only): 
```
health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/defx.nvim/
set runtimepath+=~/path/to/defx-git "https://github.com/kristijanhusak/defx-git
set runtimepath+=~/path/to/defx-icons "https://github.com/kristijanhusak/defx-icons

call defx#custom#option('_', {
      \ 'columns': 'git:icons:filename:size:time',
      \ })

```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Open neovim
 2. Open defx
 3. Switch focus between Defx and another window

## Screen shot (if possible)
Note the syntax off/on in defx window.

defx-gif

### PR DESCRIPTION
**Pull request by Shougo**
Fix #73

### CODE REVIEW

**Comment by kristijanhusak** [comment]
I updated my icons column to use this, see branch https://github.com/kristijanhusak/defx-icons/tree/highlight_commands.

It works when i open defx on vim enter, but when i select a file, and try to open it after (only `:Defx` is enough), i loose all syntax. Not sure why. Here's screenshot:

screenshot

Here are steps to reproduce:

1. Open any file `nvim README.md`
2. Open defx `:Defx`
3. Select some other file, for example `LICENCE`
4. Open defx again
5. No syntax highlighting.

**Comment by Shougo** [comment]
@kristijanhusak I have fixed the problems.  Please use the latest version.

And your column highlight implementation is very slow.
Please use `highlight_commands` interface instead.

**Comment by kristijanhusak** [comment]
@Shougo looks good now. It is much better.

**Comment by Shougo** [comment]
OK.  I will merge it later.

**Pull request merged**
