### PR TITLE
[WIP] Tree feature

### LINKED ISSUE #13: request: toggle drawer mode
I know about this http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer/

But sometimes (a lot of times) it's nice to have a drawer also, for exploring a big project. That's why I also have nerdtree besides defx. Are you open to implement such a feature?

### PR DESCRIPTION
**Pull request by Shougo**
Fix #13

### CODE REVIEW

**Comment by Shougo** [comment]
The implementation is almost done.
I will test the feature.

**Comment by kristijanhusak** [comment]
I tested it, looks good. Only one thing bothers me, not sure how hard is it to achieve it. Can mark column follow the indentation somehow?

screenshot

**Comment by Shougo** [comment]
>  Only one thing bothers me, not sure how hard is it to achieve it. Can mark column follow the indentation somehow?

Unfortunately, it cannot be supported.
Because the mark position is fixed.

> Edit: Also, is there a way to combine single mapping to do both opening/closing the tree, and opening a file, with a drop or something like that?

You can use `defx#is_directory()` for it.

**Comment by mhartington** [comment]
Tested this out. Looks like if you highlight the Root directory, it will double expand it

**Comment by petobens** [comment]
I have two questions/feature-requests:
1. Can you add something like `vimfiler_expand_tree_recursive` (to recursively expand/close leaves)?
2. Currently it's only possible to open/close a node with the cursor place at that candidate. Is it possible to open/close the node from within the leaves as in vimfiler?:
defxtree

**Comment by petobens** [comment]
I've also noticed that the tree mark is wrongly reset when closing and opening a defx buffer. With the following minimal vimrc:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
filetype plugin indent on

set splitright
set splitbelow


" Defx
call defx#custom#option('_', {
            \ 'winwidth': 20,
            \ 'split': 'vertical',
            \ 'direction': 'topleft',
            \ })

augroup ps_defx
    au!
    au FileType defx call s:defx_settings()
augroup END

function! s:defx_settings()
    nnoremap <silent><buffer><expr> zo defx#do_action('open_tree')
endfunction
```
Do:
1. Open `nvim`, run `:Defx` and open some candidate (`syntax` in the GIF below) with `zo` mapping
2. Close the defx buffer with `:bd`
3. Open `Defx` again with `:Defx` -> the mark icon in the `syntax` candidate is wrong:
defx-leave

**Comment by Shougo** [comment]
> Tested this out. Looks like if you highlight the Root directory, it will double expand it

Fixed.

> Can you add something like vimfiler_expand_tree_recursive (to recursively expand/close leaves)?

It is on todo list.  But it is low priority.

> Currently it's only possible to open/close a node with the cursor place at that candidate. Is it possible to open/close the node from within the leaves as in vimfiler?:

It also low priority.

> I've also noticed that the tree mark is wrongly reset when closing and opening a defx buffer. With the following minimal vimrc:

Fixed.

**Comment by hrsh7th** [comment]
I tested this, works great.

I have one feature requets `defx#is_directory_opened()`.

```
    nnoremap <silent><buffer><expr>h       defx#is_directory() ? defx#do_action('close_tree') : ''
    nnoremap <silent><buffer><expr>l       defx#is_directory() ? defx#do_action('open_tree') : defx#do_action('open')

```

`l` keymap is nice work.
But `h` keymap is not supports to change dir to upwards if candidate is closed.
I think, this behavior is common use-case.

**Comment by hrsh7th** [comment]
I found `defx#get_candidate()` and I tried to use this.
But it was not provided `is_open` property.

I think, providing `defx#is_directory_opened()` is one way.
But return more details from `defx#get_candidate()` may be more better way.

**Comment by Shougo** [comment]
@hrsh7th I have added `defx#is_opened_tree()` API for it.

**Comment by mhartington** [comment]
I've pulled down the latest and I'm still seeing directories being closed with the following 

```vim
  call defx#custom#option('_', {
      \ 'winwidth': 45,
      \ 'split': 'vertical',
      \ 'direction': 'topleft',
      \ 'show_ignored_files': 1,
      \ 'buffer_name': '',
      \ 'toggle': 1,
      \ 'resume': 1
      \ })
```

**Comment by Shougo** [comment]
@mhartington I have fixed the problem.

**Comment by Shougo** [comment]
Merged the feature.

**Pull request merged**
