### PR TITLE
Treat negative max_width column as absolute value, not as percentage

### PR DESCRIPTION
**Pull request by tex**
Hello Shougo,

Please consider this. It allows column to have dynamic width depending on width of
other columns and total buffer width. This makes column to always fit fully available space.
It allows right alignment of columns right to column using this negative max_width.
Looks much nicer than current percentage where the column width is always a bit off because it is percentage.

### CODE REVIEW

**Comment by tex** [comment]
If you like it, I'll update documentation too.

**Comment by tex** [comment]
I use it with this config:

```
call defx#custom#option('_', {
			\ 'columns': 'mark:indent:icon:filename:type:size:time',
			\ 'root_marker': ':',
			\ })
call defx#custom#column('filename', {
			\ 'root_marker_highlight': 'Ignore',
			\ })
call defx#custom#column('time', {
			\ 'format': "%d.%m.%y %H:%M"
			\ })

call defx#custom#column('filename', {
            \ 'min_width': 20,
            \ 'max_width': -37,
            \ })
```

I am also playing with resize after vsplit open and I am looking forward for vim's event on when resize of windows is finished to call resize there too :-)

**Comment by Shougo** [comment]
>Looks much nicer than current percentage where the column width is always a bit off because it is percentage.

I have added `max_width_percentage` instead of the negative value.

And please don't break existing `current_length` behavior.

> If you like it, I'll update documentation too.

Please update the documentation.

**Comment by Shougo** [comment]
>I am also playing with resize after vsplit open and I am looking forward for vim's event on when resize of windows is finished to call resize there too :-)

Please read this.
https://github.com/vim/vim/issues/3226

It does not exists on Vim/neovim.

**Comment by tex** [comment]
Try this @Shougo. I know about vim/vim#3226, but I still hope and would be nice to have it.

**Comment by Shougo** [comment]
Merged.

**Pull request merged**
