### PR TITLE
Custom column implementation

### PR DESCRIPTION
**Pull request by Shougo**
Fix #33

### CODE REVIEW

**Comment by AlexMasterov** [comment]
Hi @Shougo!

This commit made the plugin non-working for me :pensive:
Is this a `defx` problem? (need to open an issue?)

```viml
" Windows 10, Vim 8.1-513
" Python 3.6.7 / neovim 0.2.6, msgpack 0.5.6, msgpack-python 0.5.6

:Defx<CR>
```
```viml
[defx@yarp] error caught in request handler '_defx_start [[['C:\\Apps\\Vim\\'], {'columns': 'mark:filename:type', 'auto_cd': False, 'resume': False, 'listed': False, 'new': False, 'fnamewidth': 100, 'direction': '', 'winheight':
 0, 'profile': False, 'search': '', 'buffer_name': 'default', 'winwidth': 0, 'split': 'no', 'cursor': 1, 'toggle': False}]]'
[defx@yarp] Traceback (most recent call last):
[defx@yarp] 
[defx@yarp]   File "C:\Users\Alex\.vim\dein\.cache\vimrc\.dein\pythonx\yarp.py", line 23, in on_request
[defx@yarp]     return getattr(module_obj, method)(*args)
[defx@yarp] 
[defx@yarp]   File "C:\Users\Alex\.vim\dein\repos\github.com\Shougo\defx.nvim\rplugin\python3\defx\__init__.py", line 49, in _defx_start
[defx@yarp]     global_defx.start(args)
[defx@yarp] 
[defx@yarp]   File "C:\Users\Alex\.vim\dein\repos\github.com\Shougo\defx.nvim\rplugin\python3\defx\rplugin.py", line 33, in start
[defx@yarp]     views[0].init(paths, context, self._clipboard)
[defx@yarp] 
[defx@yarp]   File "C:\Users\Alex\.vim\dein\repos\github.com\Shougo\defx.nvim\rplugin\python3\defx\view.py", line 51, in init
[defx@yarp]     self.init_columns()
[defx@yarp] 
[defx@yarp]   File "C:\Users\Alex\.vim\dein\repos\github.com\Shougo\defx.nvim\rplugin\python3\defx\view.py", line 65, in init_columns
[defx@yarp]     for path_column in self.load_custom_columns():
[defx@yarp] 
[defx@yarp]   File "C:\Users\Alex\.vim\dein\repos\github.com\Shougo\defx.nvim\rplugin\python3\defx\view.py", line 335, in load_custom_columns
[defx@yarp]     'rplugin', 'python3', 'defx', 'column').glob('*.py')
[defx@yarp] 
[defx@yarp]   File "C:\Tools\python36\lib\pathlib.py", line 1100, in glob
[defx@yarp]     for p in selector.select_from(self):
[defx@yarp] 
[defx@yarp]   File "C:\Tools\python36\lib\pathlib.py", line 487, in select_from
[defx@yarp]     if not is_dir(parent_path):
[defx@yarp] 
[defx@yarp]   File "C:\Tools\python36\lib\pathlib.py", line 1348, in is_dir
[defx@yarp]     return S_ISDIR(self.stat().st_mode)
[defx@yarp] 
[defx@yarp]   File "C:\Tools\python36\lib\pathlib.py", line 1158, in stat
[defx@yarp]     return self._accessor.stat(self)
[defx@yarp] 
[defx@yarp]   File "C:\Tools\python36\lib\pathlib.py", line 387, in wrapped
[defx@yarp]     return strfunc(str(pathobj), *args)
[defx@yarp] 
[defx@yarp] OSError: [WinError 123]
```

**Comment by Shougo** [comment]
Yes.  You need to install the latest neovim.

**Comment by AlexMasterov** [comment]
Just because of this feature? nice..
Okay. Thanks for the reply.

**Comment by Shougo** [comment]
Sorry, I don't want to debug for Windows problem.
You can fix it.

**Comment by Shougo** [comment]
Hm...  I get the reason.  I will fix it later.

**Comment by Shougo** [comment]
I have fixed the problem.  Please use the latest version.

**Comment by AlexMasterov** [comment]
@Shougo 

Unfortunately, it didn't help, but it's a good optimization :)
It looks like the problem is that `runtimepath` on Windows can return a string with a different delimiter:
```sh
# rtp_list = self._vim.options['runtimepath'].split(',')
C:\Users\Alex\.vim/dein/repos/github.com/Shougo/dein.vim,
C:\Users\Alex\vimfiles,

# 'is_dir' and 'glob' throws an error on this line
C:\WINDOWS\system32;C:\WINDOWS
```
```python
>>> Path(r'C:\WINDOWS\system32;C:\WINDOWS')
WindowsPath('C:/WINDOWS/system32;C:/WINDOWS')

>>> Path(r'C:\WINDOWS\system32;C:\WINDOWS').is_dir()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Tools\python36\lib\pathlib.py", line 1348, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "C:\Tools\python36\lib\pathlib.py", line 1158, in stat
    return self._accessor.stat(self)
  File "C:\Tools\python36\lib\pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [WinError 123]
```

**Comment by Shougo** [comment]
Please test `Path(r'C:\WINDOWS\system32;C:\WINDOWS').exists()` on Windows.

**Comment by Shougo** [comment]
> It looks like the problem is that runtimepath on Windows can return a string with a different delimiter:

I don't understand.

And why `rtp_list` is not list in your examples?

**Comment by Shougo** [comment]
> 'is_dir' and 'glob' throws an error on this line

Why `rtp_list` includes `C:\WINDOWS\system32;C:\WINDOWS` ?
I don't understand.

**Comment by Shougo** [comment]
I think you can fix it.

**Comment by Shougo** [comment]
Please create the new issue for it.

**Comment by Shougo** [comment]
???
Why it is solved?
Please tell me the reason.

**Comment by AlexMasterov** [comment]
I found something like this in my vimrc configuration: (it's about "provide a minimal vimrc")
```vim
set runtimepath+=$PATH
```
But I've already found a similar problem: PermissionError `C:\\Documents and Settings`
The case when you open a folder without permissions is not handled, throws an error.
```
[defx@yarp]   File "C:\Users\Alex\.vim\dein\repos\github.com\Shougo\defx.nvim\rplugin\python3\defx\source\file.py", line 39, in gather_candidates
[defx@yarp]     'word': entry.name + ('/' if entry.is_dir() else ''),
[defx@yarp]
[defx@yarp]   File "C:\Tools\python36\lib\pathlib.py", line 1348, in is_dir
[defx@yarp]     return S_ISDIR(self.stat().st_mode)
[defx@yarp]
[defx@yarp]   File "C:\Tools\python36\lib\pathlib.py", line 1158, in stat
[defx@yarp]     return self._accessor.stat(self)
[defx@yarp]
[defx@yarp]   File "C:\Tools\python36\lib\pathlib.py", line 387, in wrapped
[defx@yarp]     return strfunc(str(pathobj), *args)
[defx@yarp]
[defx@yarp] PermissionError: [WinError 5]
```

**Comment by Shougo** [comment]
Hm...
It is very ugly error.
xxxx Windows.
Can you fix it?

**Comment by AlexMasterov** [comment]
Yes, but I don't program in Python professionally :)
This issue is not Windows-specific, see if/raise in [`is_dir`](https://github.com/python/cpython/blob/0185f34ddcf07b78feb6ac666fbfd4615d26b028/Lib/pathlib.py#L1339).

I propose to fix it using `try/except` or [`contextlib.suppress`](https://docs.python.org/3/library/contextlib.html#contextlib.suppress) PermissionError. 
[`os.access`](https://docs.python.org/3/library/os.html#os.access) adds overhead and may not work effectively on Windows, and not so many cases where such checks are really necessary.

It will be useful to show paths without access, but with a different color? 
..or just pass and error?

**Comment by Shougo** [comment]
I have added `safe_call()` function for it.

**Pull request merged**
