### PR TITLE
[RDY] Use nvim_buf_add_highlight()

### PR DESCRIPTION
**Pull request by Shougo**
~~It may fix syntax performance issue?~~ Yes!

I have removed all conceals.

Note:  The optimization is for neovim only.  So I recommend for you to use neovim.

### CODE REVIEW

**Comment by Shougo** [comment]
The fix is almost done.
It is a lot of faster than before!

**Comment by Shougo** [comment]
I don't test external columns.  It may have problem.
Please test.

**Comment by kristijanhusak** [comment]
This requires changes to the external columns.

**Comment by Shougo** [comment]
@kristijanhusak I need the test.  Please upload the minimal vimrc with the reproduce instruction.

**Comment by kristijanhusak** [comment]
@Shougo just add `defx-icons` as plugin and include it in columns:

`Defx -columns=indent:icons:filename`

**Comment by kristijanhusak** [comment]
@Shougo I updated icons columns according to new api, here's the PR https://github.com/kristijanhusak/defx-icons/pull/18.

Only issue is with directory icons, highlight is off by 1 char, see screenshot:
screenshot

Do you know why?

**Comment by Shougo** [comment]
Oh, I get it.  Unfortunately, I cannot fix it.
Your column syntax depends on filename syntax highlight.
It is not defined anymore.
This is variable column's(`filename` column) feature.

> This requires changes to the external columns.
So you need to add new column support.

**Comment by kristijanhusak** [comment]
@Shougo please test this branch https://github.com/kristijanhusak/defx-icons/pull/18 . Everything works except the directory highlight, it's off by 1. Do you know why?

**Comment by Shougo** [comment]
> @Shougo please test this branch kristijanhusak/defx-icons#18 . Everything works except the directory highlight, it's off by 1. Do you know why?

I have fixed the offset error.  Please use the latest version.

**Comment by kristijanhusak** [comment]
@Shougo works ok now, thanks.
Is this PR compatible with Vim? Can I do these changes to all of my columns?

**Comment by Shougo** [comment]
> Is this PR compatible with Vim? 

Yes.  The new feature is only for new neovim.

> Can I do these changes to all of my columns?

I recommend.  Because it is faster.

**Comment by kristijanhusak** [comment]
@Shougo I don't have `syntax_name` all the time. When I open defx, I have it, but when I close , and open it again, it is set to empty string. Do you know why that happens?

**Comment by Shougo** [comment]
> @Shougo I don't have syntax_name all the time. When I open defx, I have it, but when I close , and open it again, it is set to empty string. Do you know why that happens?

I have not ESP skill.
Please upload the minimal vimrc and the reproduce instructions.

**Comment by kristijanhusak** [comment]
@Shougo nevermind, it was bug in my code.

I fixed my git and icons column, so when you merge this, i'll merge my PRs.

**Comment by Shougo** [comment]
OK.  I have merged it.

**Pull request merged**
