### PR TITLE
[RFC] Session feature

### LINKED ISSUE #23: session file support
It should be implemented after tree support.

### PR DESCRIPTION
**Pull request by Shougo**
Fix #23

### CODE REVIEW

**Comment by hrsh7th** [comment]
I tried this feature.

I want to option for `add_session` that disables `input` call because my workflow.

If I start edit files in project, I would type `<F5>` that decide `current working dir` explicitly. (I uses this to `Denite file/rec` `Denite grep` dirs)

I want to `add_session` with this workflow.
But currently implementation is call `input` always.
it is bit troublesome.

p

**Comment by Shougo** [comment]
> I want to option for add_session that disables input call because my workflow.

Removed the input

**Comment by hrsh7th** [comment]
Thanks!
It's perfectly works for me!

**Comment by hrsh7th** [comment]
I think, defx/session's delete action should be `persist_actions`.
My vimrc has mapping that's `nnoremap <silent><buffer><expr>d denite#do_map('do_action', 'delete')`.
When I organize sessions, It's useful.

**Comment by Shougo** [comment]
Fixed.

**Comment by Shougo** [comment]
The implementation is done.

**Comment by hrsh7th** [comment]
Sorry I have no time to test this feature... I'm busy now with work.

In my working, Sometimes 'defx/sessions' has no listing any candidates.
I didn't know this reason.
(And Sorry, I hasn't use init.min.vim yet.)

I guess currently implementations is not load 'defx#_sessions' correctly.

It is information. feel free to ignore this post.

this feature is so great. thanks.

**Comment by Shougo** [comment]
> In my working, Sometimes 'defx/sessions' has no listing any candidates.
I didn't know this reason.

Fixed.

**Comment by hrsh7th** [comment]
Thanks!!!

I checked these fixing work.
The bugs are fixed in initial call `Denite defx/session`.

But problem is remaining when called `denite#do_map('redraw')` after `Denite defx/session`.

**Comment by Shougo** [comment]
> But problem is remaining when called denite#do_map('redraw') after Denite defx/session.

Fixed.

**Pull request merged**
